# conda env create -f environment.yml

name: agape
channels:
  - defaults
dependencies:
  - scipy
  - numpy
  - pandas
  - networkx
  - scikit-learn
  - pip:
    - biopython
    - goatools
    - mypy
    - pytest
    - pytest-cov
