# conda env create -f environment.yml

name: agape
channels:
  - defaults
dependencies:
  - python=3.6
  - scipy
  - numpy
  - pandas
  - networkx
  - scikit-learn
  - pip:
    - biopython
    # Temporary fix while PyPI version of GOATOOLS GAF reader fails
    - 'git+https://github.com/tanghaibao/goatools'
    - mypy
    - pytest
    - pytest-cov
    - '--editable=.["test"]'
